services:
  python_vue:
    build: .

    networks:
    - python_vue

    # volumes:
    # - ./vue:/app/vue
    # - ./python:/app/python

    volumes:
      - sqlite_data:/data

    # command: sh -c "cd vue && npm run serve && python python/src/main.py"
    
    ports:
    - "8080:8080"
    - "8765:8765"
    - "3000:3000"

volumes:
  sqlite_data:
    driver: local

networks: 
  python_vue:
    name: python_vue
